/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "../unity/src/unity.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_declare_array_of_integers();
extern void test_declare_array_of_integers_init_one_value();
extern void test_create_array_of_integers();
extern void test_array_designated_inits();
extern void test_array_designated_inits_range();
extern void test_create_array_of_pointers_null();


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/test_array.c");
  run_test(test_declare_array_of_integers, "test_declare_array_of_integers", 11);
  run_test(test_declare_array_of_integers_init_one_value, "test_declare_array_of_integers_init_one_value", 17);
  run_test(test_create_array_of_integers, "test_create_array_of_integers", 23);
  run_test(test_array_designated_inits, "test_array_designated_inits", 29);
  run_test(test_array_designated_inits_range, "test_array_designated_inits_range", 35);
  run_test(test_create_array_of_pointers_null, "test_create_array_of_pointers_null", 42);

  return UNITY_END();
}
