# Maketutor
# https://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/

# GCC commmand options
# https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/Invoking-GCC.html#Invoking-GCC

# -Wall
# https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/Warning-Options.html#Warning-Options

CC=gcc
CFLAGS=-I.

two_sum: two_sum.o hashmap.o singly_linked_list.o
	$(CC) -o two_sum -Wall two_sum.o hashmap.o singly_linked_list.o

